in_dir = "/home/erik/Code/extern/InvokeAI/99f/mermaid_1/frames_1"
mask_dir = "/home/erik/Code/extern/InvokeAI/99f/mermaid_1/masks_1"
scratch_dir = "/home/erik/Code/extern/InvokeAI/99f/mermaid_1/scratch_1"
out_dir = "outputs/e1_2"
width = 1024
height = 768
stride = 1
restart_from = 183

[[keyframes]]
frame = 0
seed = 2399780822
prompt = "( isometric view, 3 d printed extruded filiment, beautiful woman queen chess piece, bioluminescence, beautiful face, reflection of led lights, intricate detail, futuristic, very detailed, highly detailed background, sharpfocus, photorealism, soft diffuse autumn lights, some sun light ray, dark room wall, canon 5 d 5 0 mm lens"
scale = 17.0

[[keyframes]]
duration = 300
seed = 234590987

[[keyframes]]
duration = 300
seed = 564590987

[[keyframes]]
duration = 300
seed = 784590987
