in_dir = "seance/frames2/seance5"
out_dir = "seance/outputs/seance5"
mask_in_dir = "seance/outputs/seance5_1/masks"
width = 960
height = 576

[prompts]
shadowy_figure = "a shadowy figure sits in the darkness, ominous, foreboding, dark lighting, cinematic lighting, by evgeny lushpin, by inessa garmash, by kim jung gi"


# ==================================================
[[keyframes]]
frame = 1
input_image = "IM0001.png"
input_mask = "frame_000001.png"
prompt = "shadowy_figure"
seed = 423957
strength = 0.7
scale = 7.0
#masks = [
#    { center = [1.0, 0.0], radius = 0.35, sigmoid_k = 0.2 },
#    { center = [1.0, 0.2], radius = 0.35, sigmoid_k = 0.2 },
#    { center = [1.0, 0.4], radius = 0.35, sigmoid_k = 0.2 },
#    { center = [0.8, -0.3], radius = 0.45, sigmoid_k = 0.2 }
#]

[[keyframes]]
duration = 1
seed = "random"

[[keyframes]]
frame = 80
