in_dir = "seance/frames2/seance2"
out_dir = "seance/outputs/seance2"
mask_in_dir = "seance/masks"
width = 960
height = 576

[prompts]
picture = "a smirking witch, framed classical painting hanging on a wall, dark cinematic lighting, 30mm lens, soft focus"

# seance2_0
# 21: dark landscape painting
# 22, 23: creepy figures
# 29: weird modern art piece high on wall
# 30: woman drawing on wall
# 34: complete painting, but not integrated into the scene very well
# 65: modern art painting, pretty well integrated
# 66: blank painting, well integrated
# 68: kinda weird diptich, well integrated
# 77: a shoe, somewhat poorly integrated
# 85: surrealist painting, confusingly integrated (but I like it)

# 2_1
# 8: small portrait
# 14: bigger painting
# 30: witch hat
# 34: similar to 34 in 2_0
# 42: kind of actually Hilda? but has a blurry corner
# 65: somewhat ghostly painting
# 71: very ghostly painting, otherwise perfectly integrated
# 77: decent small painting (woman on horse in battle I think)
# 85: well integrated dark painting
# 91: little statue on wall



# ==================================================
# Seance 2
[[keyframes]]
frame = 1
input_image = "IM0001.png"
prompt = "picture"
seed = 345790
strength = 0.7
scale = 7.0
masks = [{ center = [0.73, 0.83], radius = 0.23, sigmoid_k = 0.2 }]

[[keyframes]]
duration = 1
seed = "random"

[[keyframes]]
frame = 100
