in_dir = "seance/frames2/seance6"
out_dir = "seance/outputs/seance6"
mask_in_dir = "seance/outputs/seance6_1/masks"
width = 960
height = 576

[prompts]
blue_bricks = "a blue brick wall, ultra realistic, cinematic lighting, 30mm lens, by evgeny lushpin, by esao andrews"

# 6_0
# 4 interesting mural
# 8 creepy mural
# 23 man in blue mural
# 35 blue face mural
# 42 derelict mural
# 43 mural with drawn stone blocks
# 66 crazy blue man mural
# 76 mural on exposed bricks
# interesting smaller mural
# 93 angel spirit mural

# 6_1
# 8: almost bricks...
# 15 technical posters with blue ink
# 18 sort of exposed brick, but doesn't make sense
# 26 brick texture
# 40 definitely blue bricks
# 47 ghostly bricks
# 97 blue bricks through archwa
# 100 blue bricks!

# ==================================================
[[keyframes]]
frame = 1
input_image = "IM0001.png"
input_mask = "frame_000001.png"
prompt = "blue_bricks"
seed = 345790
strength = 0.7
scale = 7.0
#masks = [{ center = [0.73, 0.83], radius = 0.23, sigmoid_k = 0.2 }]

[[keyframes]]
duration = 1
seed = "random"

[[keyframes]]
frame = 100
