in_dir = "seance/frames2/seance4"
out_dir = "seance/outputs/seance4"
mask_in_dir = "seance/outputs/seance4_1/masks"
width = 960
height = 576

[prompts]
flowers = "a vase of dead flowers on a mantlepiece, ultra realistic photo, dark cinematic lighting, highly detailed, 30mm lens, soft focus"

# 4_0
# 4 bright white bushy bouquet
# 5 kind of interesting lighting
# 6 more white flowers
# 7 candle, but not integrated well
# 10 blurry sticks
# 11 different white flowers
# 23 flowery flowers
# 26 one nice flower
# 27 nice blurry flowers
# 34 another nice bouquet


# 4_1
# 21 blurry sticks
# 23 well integrated bouquet
# 26 very well integrated bouquet
# 42 another one


# ==================================================
[[keyframes]]
frame = 1
input_image = "IM0001.png"
input_mask = "frame_000001.png"
prompt = "flowers"
seed = 3674185847
strength = 0.8
scale = 8.0

[[keyframes]]
frame = 476
seed = 1130604459
