in_dir = "seance/frames2/seance5"
out_dir = "seance/outputs/seance5"
mask_in_dir = "seance/outputs/seance5_2/masks"
width = 960
height = 576

[prompts]
shadowy_figure = "a shadowy figure sits in the darkness, ominous, foreboding, dark lighting, cinematic lighting, by evgeny lushpin, by inessa garmash, by kim jung gi"
hooded_figure = "a hooded figure grabs a candle in the dark, moody cinematic lighting, by evgeny lushpin, by inessa garmash, by kim jung gi, by gabrielle del'otto"

# 5_2
# 4 cloaked figure reaches for Hope


# ==================================================
[[keyframes]]
frame = 1
input_image = "IM0001.png"
input_mask = "frame_000001.png"
prompt = "cloaked_figure"
seed = 294357
strength = 0.7
scale = 7.0
#masks = [
#    { center = [0.9, 0.2], radius = 0.3, sigmoid_k = 0.2 },
#    { center = [1.0, 0.4], radius = 0.35, sigmoid_k = 0.2 },
#    { center = [0.9, -0.1], radius = 0.45, sigmoid_k = 0.2 }
#]

[[keyframes]]
duration = 1
seed = "random"

[[keyframes]]
frame = 80
