in_dir = "seance/frames_sun_2"
out_dir = "seance/outputs/seance6"
mask_in_dir = "seance/outputs/seance6_2/masks"
width = 960
height = 576

# python tools/dream_compiler.py seance/config/seance6.toml -m --version 2 -s 1 -e 1
# python tools/dream_compiler.py seance/config/seance6.toml -c --version 5 -s 1 -e 299

[prompts]
blue_bricks = "a blue brick wall, flickering candles in sconces, dark cinematic lighting, ultra realistic digital painting, by evgeny lushpin, by esao andrews, high contrast, 30mm lens"

# 6_0
# 4 interesting mural
# 8 creepy mural
# 23 man in blue mural
# 35 blue face mural
# 42 derelict mural
# 43 mural with drawn stone blocks
# 66 crazy blue man mural
# 76 mural on exposed bricks
# interesting smaller mural
# 93 angel spirit mural

# 6_1
# 8: almost bricks...
# 15 technical posters with blue ink
# 18 sort of exposed brick, but doesn't make sense
# 26 brick texture
# 40 definitely blue bricks
# 47 ghostly bricks
# 97 blue bricks through archwa
# 100 blue bricks!

# 6_2
# 4 plain bricks, red on left
# 5 blue bricks, sconce on right
# 6 grungy bricks, regular window on right
# 11 stone, foggy
# 12 stone, medieval window
# 13 moody room with lots of paintings (no brick)
# 20 dark brick, window or painting on right
# 32 dark small bricks, big french/gothic window on right
# 34 blue brick, eastern painting on righr
# 92 blue brick, blue light on right


# ==================================================
[[keyframes]]
frame = 1
input_image = "frame_05480.png"
input_mask = "frame_05555_mask.png"
prompt = "blue_bricks"
#seed = 1189732246 # 12
seed = 744012041 # 5
strength = 0.7
scale = 7.0
#masks = [{ center = [0.73, 0.83], radius = 0.23, sigmoid_k = 0.2 }]

[[keyframes]]
frame = 299
seed = 1904964363 # 32
#seed = 1189732246 # 12
