in_dir = "seance/backgrounds"
out_dir = "seance/outputs"
mask_in_dir = "seance/masks"
width = 960
height = 540

[prompts]
ghosts = "ghosts swirl around a seance room, psychedelic digital painting, by hannah yata, by evgeny lushpin"
candles = "a dungeon with hundreds of ancient dripping candles, piles of wax, dark cinematic lighting, flickering candlelight, intricate details, by inessa garmash, by esao andrews"


# ==================================================
# Seance 1
[[keyframes]]
frame = 1
input_image = "seance1_background.png"
prompt = "ghosts"
seed = 61305
strength = 0.5
scale = 7.0

[[keyframes]]
frame = 158
seed = 73425
