in_dir = "seance/frames_sun_2/"
out_dir = "seance/outputs/seance2"
mask_in_dir = "seance/outputs/seance2_3/masks"
width = 960
height = 576

# python tools/dream_compiler.py seance/config/seance2.toml -m --version 4 -s 1 -e 1
# python tools/dream_compiler.py seance/config/seance2.toml -c --version 4 -s 1 -e 192

[prompts]
picture = "a smirking witch, framed classical painting hanging on a wall, dark cinematic lighting, 30mm lens, soft focus"
clocks = "a wall clock with too many hands, physical spaces anchor our spirits throgh time"

# seance2_0
# 21: dark landscape painting
# 22, 23: creepy figures
# 29: weird modern art piece high on wall
# 30: woman drawing on wall
# 34: complete painting, but not integrated into the scene very well
# 65: modern art painting, pretty well integrated
# 66: blank painting, well integrated
# 68: kinda weird diptich, well integrated
# 77: a shoe, somewhat poorly integrated
# 85: surrealist painting, confusingly integrated (but I like it)

# 2_1
# 8: small portrait
# 14: bigger painting
# 30: witch hat
# 34: similar to 34 in 2_0
# 42: kind of actually Hilda? but has a blurry corner
# 65: somewhat ghostly painting
# 71: very ghostly painting, otherwise perfectly integrated
# 77: decent small painting (woman on horse in battle I think)
# 85: well integrated dark painting
# 91: little statue on wall

# 2_2
# 9: crazy clock with rune symbols 1797633953
# 20: oculus clock 2729731671
# 45 evil spirit clock 2444795489
# 11: bigger sticky tree clock 1586991152
# 17: another spirit clock 1916318397
# 25: picasso clock 4009120808
# 34: aquatic clock 3305617673

# 2_3
# 56 1436497366
# 90 2105863265
# 59 427864619
# 45 melty clock! 3022033244

# 10 meh
# 42 anchor
# 48
# 49
# 103
# 104

#seance/outputs/seance2_3/frames/frame_000056.png: --prompt_idx 1 -s 50 -S 1436497366 -W 960 -H 576 -C 7.0 -I seance/frames_sun_2/frame_02736.png -A k_lms -M seance/outputs/seance2_3/masks/frame_000001.png -f 0.7 -V 2444795489:0.284
#seance/outputs/seance2_4/frames/frame_000001.png: --prompt_idx 1 -s 50 -S 1436497366 -W 960 -H 576 -C 7.0 -I seance/frames_sun_2/frame_02736.png -A k_lms -M seance/outputs/seance2_3/masks/frame_000001.png -f 0.7

# ==================================================
# Seance 2
[[keyframes]]
frame = 1
input_image = "frame_02736.png"
input_mask = "frame_000001.png"
prompt = "clocks"
seed = 1436497366
strength = 0.7
scale = 7.0
#masks = [{ center = [0.74, 0.83], radius = 0.23, sigmoid_k = 0.2 }]

[[keyframes]]
frame = 64
seed = 2105863265

[[keyframes]]
frame = 128
seed = 427864619

[[keyframes]]
frame = 192
seed = 3022033244
