in_dir = "seance/frames"
out_dir = "seance/outputs"
mask_in_dir = "seance/masks"
width = 960
height = 540

[prompts]
ghosts = "ghosts swirl around a seance room, psychedelic digital painting, by hannah yata, by evgeny lushpin"


# ==================================================
# Seance 1
[[keyframes]]
frame = 1
input_image = "seance1/IM{0001}.png"
input_mask = "seance1/masks_sum/frame_{000001}.png"
prompt = "ghosts"
seed = 1234
strength = 0.7
scale = 7.0

[[keyframes]]
frame = 158
