in_dir = "seance/frames_sun_2/"
out_dir = "seance/outputs/seance4"
mask_in_dir = "seance/outputs/seance4_5/masks"
width = 960
height = 576

# python tools/dream_compiler.py seance/config/seance4.toml -m --version 5 -s 1 -e 1
# python tools/dream_compiler.py seance/config/seance4.toml -c --version 5 -s 1 -e 474

[prompts]
flowers = "small white flowers in an organic glass vase, dark cinematic lighting, ultra realistic digital painting, highly detailed, by evgeny lushpin, by alex gray"

# 4_0
# 4 bright white bushy bouquet
# 5 kind of interesting lighting
# 6 more white flowers
# 7 candle, but not integrated well
# 10 blurry sticks
# 11 different white flowers 39611231
# 23 flowery flowers 3674185847
# 26 one nice flower 1130604459
# 27 nice blurry flowers
# 34 another nice bouquet
# 36 very cool bouquet
# 38 one bright flower
# 41 very good flower
# 55 bigger bouquet
# 57 nice big flower
# 59 another single flower
# 65 another single flower

# 4_1
# 21 blurry sticks
# 23 well integrated bouquet
# 26 very well integrated bouquet
# 42 another one
# 55 big blurry bouquet
# 60 beautiful dead plants!
# 98 cool diverse bouquet


# ==================================================
[[keyframes]]
frame = 1
input_image = "frame_03715.png"
#input_mask = "frame_03715_mask.png"
prompt = "flowers"
seed = 346299947
strength = 0.7
scale = 7.0
masks = [
    { center = [0.2, 0.76], radius = 0.2, sigmoid_k = 0.2 },
    { center = [0.62, 0.77], radius = 0.2, sigmoid_k = 0.2 }
]

[[keyframes]]
duration = 1
seed = "random"

[[keyframes]]
frame = 100

#[[keyframes]]
#frame = 476
#seed = 1130604459
