in_dir = "seance/frames"
out_dir = "seance/outputs"
mask_in_dir = "seance/masks"
width = 960
height = 540

[prompts]
ghosts = "ghosts swirl around a seance room, psychedelic digital painting, by hannah yata, by evgeny lushpin"
candles = "a dungeon with hundreds of ancient dripping candles, piles of wax, dark cinematic lighting, flickering candlelight, intricate details, by inessa garmash, by esao andrews"


# ==================================================
# Seance 1
[[keyframes]]
frame = 1
input_image = "seance1/IM{0001}.png"
input_mask = "seance1/masks_sum/frame_{000001}.png"
prompt = "candles"
seed = 61305
strength = 0.6
scale = 7.0

[[keyframes]]
frame = 158
