in_dir = "projects/ice_phage/not_used"
out_dir = "projects/ice_phage/outputs/bio_valve/"
mask_in_dir = "projects/ice_phage/not_used"
width = 960
height = 576

[prompts]
bio_valve = "biological valve body megastructure in the style of dr. seuss, intricate colorful masterpiece, hyper detailed, hd"

[[keyframes]]
frame = 1
seed = 128345087
prompt = "bio_valve"
scale = 8.0
set_color_reference = true

[[keyframes]]
duration = 1
seed = "random"
input_image = "previous"
correct_colors = true
strength = 0.8
transform.zoom = 1.02
transform.translate = [3.0, 0.0]
transform.rotate = -0.005

[[keyframes]]
duration = 160
transform.zoom = 0.98
transform.translate = [2.0, -4.0]
transform.rotate = 0.0

[[keyframes]]
duration = 140
transform.zoom = 1.0
transform.translate = [3.0, 2.0]
transform.rotate = 0.0

[[keyframes]]
duration = 175
transform.zoom = 1.02
transform.translate = [0.0, 2.0]
transform.rotate = 0.007

[[keyframes]]
duration = 155
transform.zoom = 1.0
transform.translate = [5.0, 3.0]
transform.rotate = 0.0

[[keyframes]]
duration = 155
transform.zoom = 1.03
transform.translate = [3.0, 2.0]
transform.rotate = -0.01

[[keyframes]]
duration = 170
