in_dir = "projects/ice_phage/not_used"
out_dir = "projects/ice_phage/outputs/bio_valve/"
mask_in_dir = "projects/ice_phage/not_used"
width = 960
height = 576

[prompts]
bio_valve = "biological valve body megastructure in the style of dr. seuss, intricate colorful masterpiece, hyper detailed, hd"

[[keyframes]]
frame = 1
seed = 98723456812121
prompt = "bio_valve"
scale = 8.0
set_color_reference = true

[[keyframes]]
duration = 1
seed = "random"
input_image = "previous"
correct_colors = true
strength = 0.5
transform.zoom = 1.03
transform.translate = [0.0, 0.0]
transform.rotate = 0.0

[[keyframes]]
duration = 150
animation.zoom = 1.0
animation.translate = [0.0, -4.0]
animation.rotate = 0.0

[[keyframes]]
duration = 160
animation.zoom = 0.98
animation.translate = [0.0, 2.0]
animation.rotate = 0.0

[[keyframes]]
duration = 175
animation.zoom = 0.98
animation.translate = [0.0, 2.0]
animation.rotate = 1.0

[[keyframes]]
duration = 155
animation.zoom = 1.0
animation.translate = [5.0, 3.0]
animation.rotate = 0.0

[[keyframes]]
duration = 155
animation.zoom = 1.03
animation.translate = [3.0, 2.0]
animation.rotate = 1.0

[[keyframes]]
duration = 170
