in_dir = "projects/ice_phage/not_used"
out_dir = "projects/ice_phage/outputs/brain_tissue/"
mask_in_dir = "projects/ice_phage/not_used"
width = 960
height = 576

[prompts]
brain_tissue = "confocal microscope image of brain tissue overwhelmed with viruses, by kim jung gi, by hannah yata, by killian eng, by evgeny lushpin, hyper detailed digital painting"

[[keyframes]]
frame = 1
seed = 209043567
prompt = "brain_tissue"
scale = 8.0
set_color_reference = true

[[keyframes]]
duration = 1
seed = "random"
input_image = "previous"
correct_colors = true
strength = 0.7
transform.zoom = 1.01
transform.translate = [-3.0, 0.0]
transform.rotate = 0.0

[[keyframes]]
duration = 160
transform.zoom = 1.01
transform.translate = [-3.0, -1.0]
transform.rotate = 0.005

[[keyframes]]
duration = 140
transform.zoom = 1.0
transform.translate = [4.0, 3.0]
transform.rotate = 0.0

[[keyframes]]
duration = 175
transform.zoom = 1.02
transform.translate = [3.0, 2.0]
transform.rotate = -0.007

[[keyframes]]
duration = 155
transform.zoom = 1.0
transform.translate = [-5.0, 3.0]
transform.rotate = 0.004

[[keyframes]]
duration = 120
transform.zoom = 0.98
transform.translate = [-3.0, 2.0]
transform.rotate = 0.007

[[keyframes]]
duration = 170
