in_dir = "projects/ice_phage/not_used"
out_dir = "projects/ice_phage/outputs/complex_virus/"
mask_in_dir = "projects/ice_phage/not_used"
width = 960
height = 576

[prompts]
virus1 = "an icosahedral virus on a long stalk attacks bacteria, electron microscope image, by kim jung gi"
virus2 = "a virus with a head and tail, electron microscope image, by kim jung gi"
virus3 = "an icosahedral virus with a head and tail and long stalk, electron microscope image, by kim jung gi"

[[keyframes]]
frame = 1
seed = 176892345
prompt = "virus1"
scale = 8.0
set_color_reference = true

[[keyframes]]
duration = 1
seed = "random"
input_image = "previous"
correct_colors = true
strength = 0.7
transform.zoom = 1.02             # multiplicative factor per frame
transform.translate = [2.0, 0.0]  # pixels per frame for X and Y
transform.rotate = 0.0            # revolutions per frame (positive is CCW)

[[keyframes]]
duration = 120
transform.zoom = 1.02
transform.translate = [2.0, 0.0]
transform.rotate = -0.01

[[keyframes]]
duration = 120
transform.zoom = 1.0
transform.translate = [6.0, 0.0]
transform.rotate = 0.0

[[keyframes]]
duration = 140
transform.zoom = 0.98
transform.translate = [3.0, 1.0]
transform.rotate = 0.02

[[keyframes]]
duration = 160
transform.zoom = 1.0
transform.translate = [5.0, 3.0]
transform.rotate = 0.02

[[keyframes]]
duration = 100
transform.zoom = 1.02
transform.translate = [0.0, -2.0]
transform.rotate = 0.0

[[keyframes]]
duration = 150
