in_dir = "projects/ice_phage/not_used"
out_dir = "projects/ice_phage/outputs/ice_sculpture/"
mask_in_dir = "projects/ice_phage/not_used"
width = 960
height = 576

[prompts]
sculpture = "a burning man sculture made of blueish transparent glass, winter, ray traced refraction, cold colors, cinematic lighting, rim light, high contrast, saturated colors, by tooth wu, by evgeny lushpin, ultra realistic 8k render, cgsociety"

[[keyframes]]
frame = 1
seed = 1780130923
prompt = "sculpture"
scale = 8.0
set_color_reference = true

[[keyframes]]
duration = 1
seed = "random"
input_image = "previous"
correct_colors = true
strength = 0.5
transform.zoom = 0.98             # multiplicative factor per frame
transform.translate = [0.0, 3.0]  # pixels per frame for X and Y
transform.rotate = -0.02            # degrees per frame (positive is CCW)

#[[keyframes]]
#duration = 123
#transform.zoom = 1.0
#transform.translate = [5.0, 0.0]
#transform.rotate = 0.0
#
#[[keyframes]]
#duration = 132
#transform.zoom = 1.03
#transform.translate = [0.0, 2.0]
#transform.rotate = 0.03
#
#[[keyframes]]
#duration = 168
#transform.zoom = 1.0
#transform.translate = [0.0, 6.0]
#transform.rotate = 0.0
#
#[[keyframes]]
#duration = 87
#transform.zoom = 1.0
#transform.translate = [0.0, 6.0]
#transform.rotate = -0.03
#
#[[keyframes]]
#duration = 106
#transform.zoom = 0.98
#transform.translate = [0.0, -2.0]
#transform.rotate = -0.01

[[keyframes]]
duration = 110
