in_dir = "projects/ice_phage/not_used"
out_dir = "projects/ice_phage/outputs/snow_playa/"
mask_in_dir = "projects/ice_phage/not_used"
width = 960
height = 576

[prompts]
snow_playa = "burning man in the snow. intricate artwork. by Tooth Wu, wlop, beeple, dan mumford. octane render, trending on artstation, greg rutkowski very coherent symmetrical artwork. cinematic, hyper realism, high detail, octane render, 8k, iridescent accents"

[[keyframes]]
frame = 1
seed = 983740
prompt = "snow_playa"
scale = 8.0

[[keyframes]]
duration = 150
seed = 1129075

[[keyframes]]
duration = 150
seed = 3204759

[[keyframes]]
duration = 150
seed = 105027

[[keyframes]]
duration = 150
seed = 48765498
set_color_reference = true

[[keyframes]]
duration = 1
seed = "random"
input_image = "previous"
correct_colors = true
strength = 0.5
transform.zoom = 1.03
transform.translate = [0.0, 0.0]
transform.rotate = 0.0

[[keyframes]]
duration = 150
animation.zoom = 1.0
animation.translate = [0.0, -4.0]
animation.rotate = 0.0

[[keyframes]]
duration = 160
animation.zoom = 0.98
animation.translate = [0.0, 2.0]
animation.rotate = 0.0

[[keyframes]]
duration = 175
animation.zoom = 0.98
animation.translate = [0.0, 2.0]
animation.rotate = 1.0

[[keyframes]]
duration = 155
animation.zoom = 1.0
animation.translate = [5.0, 3.0]
animation.rotate = 0.0

[[keyframes]]
duration = 155
animation.zoom = 1.03
animation.translate = [3.0, 2.0]
animation.rotate = -1.0

[[keyframes]]
duration = 170
