in_dir = "projects/ice_phage/not_used"
out_dir = "projects/ice_phage/outputs/snow_playa/"
mask_in_dir = "projects/ice_phage/not_used"
width = 960
height = 576

[prompts]
snow_playa = "burning man in the snow. intricate artwork. by Tooth Wu, wlop, beeple, dan mumford. octane render, trending on artstation, greg rutkowski very coherent symmetrical artwork. cinematic, hyper realism, high detail, octane render, 8k, iridescent accents"

[[keyframes]]
frame = 1
seed = 97092864
prompt = "snow_playa"
scale = 8.0

[[keyframes]]
duration = 150
seed = 3338490

[[keyframes]]
duration = 150
seed = 1080234798

[[keyframes]]
duration = 150
seed = 19876666

[[keyframes]]
duration = 150
seed = 654418794
set_color_reference = true

[[keyframes]]
duration = 1
seed = "random"
input_image = "previous"
correct_colors = true
strength = 0.6
transform.zoom = 1.03
transform.translate = [0.0, 0.0]
transform.rotate = 0.0

[[keyframes]]
duration = 150
transform.zoom = 1.0
transform.translate = [4.0, 0.0]
transform.rotate = 0.0

[[keyframes]]
duration = 160
transform.zoom = 0.98
transform.translate = [0.0, 2.0]
transform.rotate = 0.01

[[keyframes]]
duration = 120
transform.zoom = 0.98
transform.translate = [0.0, 2.0]
transform.rotate = 0.015

[[keyframes]]
duration = 40
transform.zoom = 0.98
transform.translate = [0.0, 2.0]
transform.rotate = 0.02

[[keyframes]]
duration = 50
transform.zoom = 1.0
transform.translate = [5.0, 3.0]
transform.rotate = 0.0

[[keyframes]]
duration = 155
transform.zoom = 1.03
transform.translate = [3.0, 2.0]
transform.rotate = -0.015

[[keyframes]]
duration = 170
