in_dir = "/home/erik/Code/extern/InvokeAI/99f/mermaid_1/frames_1"
mask_dir = "/home/erik/Code/extern/InvokeAI/99f/mermaid_1/masks_1"
scratch_dir = "/home/erik/Code/extern/InvokeAI/99f/mermaid_1/scratch_1"
out_dir = "outputs/e1_14"
width = 1024
height = 768
stride = 1
restart_from = 166

[[keyframes]]
frame = 0
seed = 1373526326
prompt = "futuristic cyclops sunglasses layed on a marble table, 3d render, amazing detail, studio lighting, ray tracing, award winning"
scale = 7

[[keyframes]]
duration = 300
seed = 234590987

[[keyframes]]
duration = 300
seed = 564590987

[[keyframes]]
duration = 300
seed = 784590987
