in_dir = "n/a"
mask_dir = "n/a"
scratch_dir = "transition of 20 - 18 - 19 - different seed, less strength"
out_dir = "outputs/e1_45"
width = 1024
height = 768
stride = 1

[[keyframes]]
frame = 1
seed = 234590987
prompt = "shattered glass, space, low poly, colorful, oil, expressionism, man, rain"
scale = 10.0
strength = 0.5
steps = 50
color_coherence = "LAB"

[[keyframes]]
duration = 1
seed = "random"
animation.zoom = 1.02             # multiplicative factor per frame
animation.translate = [2.0, 0.0]  # pixels per frame for X and Y
animation.rotate = -1.0           # degrees per frame (positive is CCW)
  
[[keyframes]]
duration = 100
animation.zoom = 0.98
animation.translate = [0.0, -2.0]
animation.rotate = -0.1

[[keyframes]]
duration = 100
animation.zoom = 1.0
animation.translate = [-5.0, 0.0]
animation.rotate = 0.0

[[keyframes]]
duration = 80
prompt = "a colorful background with a lot of bubbles, concept art by rhads, behance contest winner, space art, outrun, psychedelic, retrowave"
animation.zoom = 1.02
animation.translate = [0.0, -2.0]
animation.rotate = 1.0

[[keyframes]]
duration = 100
prompt = "chromatic waves, synthwave, aesthetic, sharp focus, 8k"
