in_dir = "n/a"
mask_dir = "n/a"
out_dir = "outputs/lava/frames"
width = 1024
height = 768
stride = 1

[[keyframes]]
frame = 0
seed = 6890234
prompt = "a primordial landscape, lava ocean meets obsidian mountains, night sky with bright stars, steam, sparks, wide field of view, acrylic paint, brush strokes, godrays, ultra detailed, high resolution, art by inessa garmash, trending on artstation"
scale = 7.5
strength = 0.5
steps = 50

[[keyframes]]
duration = 1
seed = "random"

[[keyframes]]
duration = 100
