in_dir = "n/a"
mask_dir = "n/a"
out_dir = "outputs/lava/frames"
width = 512
height = 512
stride = 1

[[keyframes]]
frame = 0
seed = 6890234
prompt = "primordial lava landscape, obsidian, abstract, flowing, acrilic paint, brush strokes, heavenly atmosphere, ultra detailed, high resolution, trending on artstation"
scale = 7.5
strength = 0.5
steps = 50

[[keyframes]]
duration = 1
seed = "random"

[[keyframes]]
duration = 100
