in_dir = "n/a"
mask_dir = "n/a"
out_dir = "outputs/e1_41"
width = 1024
height = 768
stride = 1

[[keyframes]]
frame = 0
seed = 405867197
prompt = "a primordial landscape, lava ocean meets obsidian mountains, night sky with bright stars, steam, sparks, wide field of view, acrylic paint, brush strokes, godrays, ultra detailed, high resolution, art by inessa garmash, trending on artstation"
scale = 8.0
strength = 0.5
steps = 50
color_coherence = "LAB"

[[keyframes]]
duration = 1
seed = "random"
animation.zoom = 1.05             # multiplicative factor per frame
animation.translate = [3.0, 2.0]  # pixels per frame for X and Y
animation.rotate = -2.0           # degrees per frame (positive is CCW)

[[keyframes]]
duration = 500
animation.zoom = 0.85
animation.translate = [0.0, -3.0]
animation.rotate = -0.4
