in_dir = "n/a"
mask_dir = "n/a"
out_dir = "outputs/neon/frames"
width = 1024
height = 768
stride = 1

[[keyframes]]
frame = 1
seed = 1291772199
prompt = "neon hieroglyphics intertwined with shiny metal sculpture, onyx, pink, highly detailed, ultra realistic, octane render 8k, by guerrino boatto"
scale = 10.0
strength = 0.5
steps = 50
color_coherence = "LAB"

[[keyframes]]
duration = 1
seed = "random"
animation.zoom = 1.02             # multiplicative factor per frame
animation.translate = [2.0, 0.0]  # pixels per frame for X and Y
animation.rotate = -1.0           # degrees per frame (positive is CCW)

[[keyframes]]
duration = 100
animation.zoom = 0.98
animation.translate = [0.0, -2.0]
animation.rotate = -0.1

[[keyframes]]
duration = 100
animation.zoom = 1.0
animation.translate = [-5.0, 0.0]
animation.rotate = 0.0

[[keyframes]]
duration = 120
prompt = "neon sculptures in the martian desert, shiny metal statues, background of rugged onyx rocks, pink, highly detailed, ultra realistic, octane render 8k by kilian eng and guerrino boatto"
animation.zoom = 1.02
animation.translate = [-2.0, -1.0]
animation.rotate = 0.0

[[keyframes]]
duration = 100
prompt = "neon sculptures in the martian desert, shiny metal statues, background of rugged onyx rocks, pink, highly detailed, ultra realistic, octane render 8k by kilian eng and guerrino boatto"
