in_dir = "n/a"
mask_dir = "n/a"
scratch_dir = "/home/erik/Code/extern/InvokeAI/outputs/zoom/00/scratch"
out_dir = "outputs/zoom/00/out"
width = 512
height = 512
stride = 1

[[keyframes]]
frame = 0
seed = 6890234
prompt = "a lush redwood forest with glowing orange mushrooms, verdant ferns, fog, heavenly light rays filtering through leaves, highly detailed digitial painting, cinematic lighting, by artgerm, loish, greg rutkoski, and alphonse mucha"
scale = 7.5
strength = 0.5
masks = []

[[keyframes]]
duration = 1
seed = "random"
animation.zoom = 1.02             # multiplicative factor per frame
animation.translate = [0.0, 0.0]  # pixels per frame for X and Y
animation.rotate = 0.0            # degrees per frame

[[keyframes]]
duration = 100
