in_dir = "alice/frames"
out_dir = "alice/outputs/mask_test"
width = 960
height = 720

[prompts]
tombstone = "an old tombstone in a grassy graveyard, weathered, by Kilian Eng and Esao Andrews"
jackrabbit = "a portrait of jack skelington as a rabbit, demon eyes, steampunk, dark atmospheric, by Kilian Eng and Esao Andrews"
witch = "portrait of a wicked witch with blonde hair crying blood, by greg rutkowski, by ross tran, by fenghua zhong, horror, octane, soft render, oil on canvas, moody lighting, high contrast, cinematic, trending on artstation, masterpiece"
skull = "a weathered skull in a grassy graveyard, by Kilian Eng, by Esao Andrews, cinematic, high contrast"

[[keyframes]]
frame = 1186
input_image = "rabbit_hole/IM1186.png"
prompt = "witch"
seed = 1640273403 # golden seed for frame 1186/1187
masks = [
    { center = [0.74, 0.666], radius = 0.2 }
]
strength = 0.65


[[keyframes]]
frame = 1187
input_image = "rabbit_hole/IM1200.png"
masks = [
    { center = [0.79, 0.52], radius = 0.2 }
]
fill_mask = true
seed = "random"
strength = 0.5

[[keyframes]]
duration = 1
