in_dir = "alice/frames"
out_dir = "alice/outputs/rabbit_hole"
width = 960
height = 720

[prompts]
tombstone = "an old tombstone in a grassy graveyard, weathered, by Kilian Eng and Esao Andrews"
jackrabbit = "a portrait of jack skelington as a rabbit, demon eyes, steampunk, dark atmospheric, by Kilian Eng and Esao Andrews"
witch = "portrait of a wicked witch with blonde hair crying blood, by greg rutkowski, by ross tran, by fenghua zhong, horror, octane, soft render, oil on canvas, moody lighting, high contrast, cinematic, trending on artstation, masterpiece"
witch2 = "portrait of a wicked witch with blonde hair and countless sharp teeth crying blood, by greg rutkowski, by ross tran, by fenghua zhong, horror, octane, soft render, oil on canvas, moody lighting, high contrast, cinematic, trending on artstation, masterpiece"
witch3 = "a painting of a blonde witch in a blue dress splattered with blood crawling in a tunnel in the catacombs, alice in wonderland, dramatic lighting, shattered bones, chiaroscuro, high detail, painted by greg rutkowski, painted by igor kieryluk, painted by bobby chiu, trending on artstation"
skull = "a weathered skull in a grassy graveyard, by Kilian Eng, by Esao Andrews, cinematic, high contrast"
pit = "the cheshire cat stares down a deep pit lined with decaying human skulls, fire consumes all, smiling as the viewer falls to their death, highly detailed matte painting, by kilian eng, by esao andrews"
falling = "a blonde witch in a blue dress falls into a dimensional rift, alice in wonderland, horror, cinematic, dynamic lighting, high contrast, by Raphael Lacoste and Delphin Enjolras and William Bliss Baker"


# ==================================================
# alice and cat relaxing on grass
[[keyframes]]
frame = 138
input_image = "rabbit_hole/IM{0138}.png"
prompt = "skull"
seed = 2922644564 # actually gives a skull (only one out of 100 random seeds)
# previously explored seeds for tombstone prompt: 438989805 1136108454
scale = 8.0
strength = 0.0
masks = [
    { center = [0.95, 0.4], radius = 0.25 }
]
steps = 50

[[keyframes]]
frame = 148
strength = 0.6

[[keyframes]]
frame = 160
strength = 0.8

[[keyframes]]
frame = 179
strength = 0.8

[[keyframes]]
frame = 188
strength = 0.6

[[keyframes]]
frame = 189
strength = 0.0
masks = []

# zoom in on alice
[[keyframes]]
frame = 190
prompt = "tombstone"
seed = 438989805 # gives a coherent tombstone
masks = [
    { center = [0.95, 0.4], radius = 0.25 }
    { center = [0.95, 0.5], radius = 0.25 }
    { center = [0.95, 0.6], radius = 0.25 }
]
strength = 0.8

[[keyframes]]
frame = 222

[[keyframes]]
frame = 231
strength = 0.666

# camera starts panning up
[[keyframes]]
frame = 232
strength = 0.0
masks = []


# ==================================================
# rabbit checks pocketwatch then starts running
[[keyframes]]
frame = 242
strength = 0.0
masks = []
# nothing planned

# rabbit checks pocketwatch
[[keyframes]]
frame = 257
prompt = "jackrabbit"
seed = 232288432 # clock eye
#seed = 3853414560 # very coherent rabbit face
strength = 0.0
masks = [
    { center = [0.5, 0.55], radius = 0.3 }
]

[[keyframes]]
frame = 259
masks = [
    { center = [0.4, 0.5], radius = 0.3 }
]
strenth = 0.2

[[keyframes]]
frame = 260
masks = [
    { center = [0.38, 0.68], radius = 0.35 }
]
strength = 0.3

[[keyframes]]
frame = 266
strength = 0.6
masks = [
    { center = [0.35, 0.68], radius = 0.4 }
]

[[keyframes]]
frame = 267
strength = 0.7

[[keyframes]]
frame = 277

[[keyframes]]
frame = 287
strength = 0.0
masks = []


# ==================================================
# alice crawls into the rabbit hole (viewed from front)
[[keyframes]]
frame = 1128
prompt = "witch"
seed = 1640273403 # golden seed for frame 1186/1187
strength = 0.0
masks = []

[[keyframes]]
frame = 1172
masks = [
    { center = [0.77, 0.566], radius = 0.2 }
]

[[keyframes]]
frame = 1177
masks = [
    { center = [0.77, 0.566], radius = 0.2 }
]
strength = "interpolate"

[[keyframes]]
frame = 1182
masks = [
    { center = [0.74, 0.666], radius = 0.2 }
]
strength = 0.65

[[keyframes]]
frame = 1197
masks = [
    { center = [0.75, 0.666], radius = 0.2 }
]

[[keyframes]]
frame = 1198
masks = [
    { center = [0.77, 0.6], radius = 0.2 }
]

[[keyframes]]
frame = 1200
masks = [
    { center = [0.79, 0.52], radius = 0.2 }
]

[[keyframes]]
frame = 1206
masks = [
    { center = [0.79, 0.5], radius = 0.2 }
]

[[keyframes]]
# she starts moving to the right here (eventually leaving the frame)
frame = 1220
masks = []
strength = 0.0


# ==================================================
# alice crawls deeper into the rabbit hole (side view)
[[keyframes]]
frame = 1264
input_image = "rabbit_hole/IM{1264}.png"
prompt = "witch3"
strength = 0.0
seed = 2390586

[[keyframes]]
frame = 1310
strength = 0.0

[[keyframes]]
frame = 1360
strength = 0.6

[[keyframes]]
frame = 1383
strength = 0.6

# alice falls 1390ish
[[keyframes]]
frame = 1393
strength = 0.0

#cat enters frame to look, slips down slope but catches herself
[[keyframes]]
frame = 1412

#peers after alice
[[keyframes]]
frame = 1500

# ==================================================
# cat peers down, as seen by alice (cat recedes into distance)
[[keyframes]]
frame = 1562
input_image = "rabbit_hole/IM{1562}.png"
prompt = "pit"
seed = 3472986395
strength = 0.0
masks = []

[[keyframes]]
frame = 1575
strength = 0.5
set_color_reference = true

[[keyframes]]
frame = 1576
seed = "random"
input_image = "previous"
strength = 0.5
correct_colors = true
transform.zoom = 0.97
transform.translate = [-3.0, 6.0]
transform.rotate = 0.0

[[keyframes]]
frame = 1594
transform.zoom = 0.96
transform.translate = [0.0, 5.0]
transform.rotate = 0.05

# ==================================================
# alice tumbles through darkness
[[keyframes]]
frame = 1618
transform = "none"
input_image = "rabbit_hole/IM{1618}.png"
prompt = "falling"
strength = 0.0
seed = 29348756

# dress acts as parachute
[[keyframes]]
frame = 1660
strength = 0.0

[[keyframes]]
frame = 1680
strength = 0.6

[[keyframes]]
frame = 1715
strength = 0.6

# ==================================================
# zoom in
[[keyframes]]
frame = 1716

# ==================================================
# alice's feet from her viewpoint
[[keyframes]]
frame = 1762

# ==================================================
# back to zoomed in side view
[[keyframes]]
frame = 1798
#1895: starts getting darker
#1950: stable darkness

# ==================================================
# zooms out a bit
[[keyframes]]
frame = 1972
#2012: lamp appears at bottom
#2045: alice turns on lamp, other furniture is visible

# ==================================================
# cuts to lower view, only alice's legs in frame, mirror on right side
[[keyframes]]
frame = 2210
#2335: alice grabs book

# ==================================================
# close up of alice reading book
[[keyframes]]
frame = 2368

# ==================================================
# zoom back out
[[keyframes]]
frame = 2468
#2520: grandfather clock goes by on right, bent chimney on left
#2545: alice falls into chair
#2680: kettle over fire in stove on right
#2742: alice slips out of chair

# ==================================================
# only alice's feet visible, funnel below
[[keyframes]]
frame = 2810
#2870: halfway through funnel
#2900: narrowest point
#2940: restabilized, map coming into view
#3000: looking at map (alice is upside down)

# ==================================================
# zoom in, upside down alice looking at map
[[keyframes]]
frame = 3008
#3070: map leaving view

# ==================================================
# rabbit running away (upside down since alice is)
[[keyframes]]
frame = 3160
