in_dir = "alice/frames"
out_dir = "alice/outputs/rabbit_hole"
width = 960
height = 720

[prompts]
tombstone = "an old tombstone in a grassy graveyard, weathered, by Kilian Eng and Esao Andrews"
jackrabbit = "a portrait of jack skelington as a rabbit, demon eyes, steampunk, dark atmospheric, by Kilian Eng and Esao Andrews"
witch = "portrait of a wicked witch with blonde hair crying blood, by greg rutkowski, by ross tran, by fenghua zhong, horror, octane, soft render, oil on canvas, moody lighting, high contrast, cinematic, trending on artstation, masterpiece"


# ==================================================
# alice and cat relaxing on grass
[[keyframes]]
frame = 138
input_image = "rabbit_hole/IM{0138}.png"
# interesting seeds: 438989805 1136108454
seed = 1136108454
prompt = "tombstone"
scale = 8.0
strength = 0.8
steps = 50
masks = [
    { center = [0.95, 0.3], radius = 0.25 }
    { center = [0.95, 0.4], radius = 0.25 }
    { center = [0.95, 0.5], radius = 0.25 }
    { center = [0.95, 0.6], radius = 0.25 }
]

# zoom in on alice
[[keyframes]]
frame = 190
seed = 438989805
masks = [
    { center = [0.95, 0.4], radius = 0.25 }
    { center = [0.95, 0.5], radius = 0.25 }
    { center = [0.95, 0.6], radius = 0.25 }
]

[[keyframes]]
frame = 222

[[keyframes]]
frame = 231
strength = 0.666

# camera starts panning up
[[keyframes]]
frame = 232
strength = 0.0
masks = []


# ==================================================
# rabbit checks pocketwatch then starts running
[[keyframes]]
frame = 242
strength = 0.0
masks = []
# nothing planned

# rabbit checks pocketwatch
[[keyframes]]
frame = 257
prompt = "jackrabbit"
seed = 232288432 # clock eye
#seed = 3853414560 # very coherent rabbit face
strength = 0.0
masks = [
    { center = [0.5, 0.55], radius = 0.3 }
]

[[keyframes]]
frame = 259
masks = [
    { center = [0.4, 0.5], radius = 0.3 }
]
strenth = 0.2

[[keyframes]]
frame = 260
masks = [
    { center = [0.38, 0.68], radius = 0.35 }
]
strength = 0.3

[[keyframes]]
frame = 266
strength = 0.6
masks = [
    { center = [0.35, 0.68], radius = 0.4 }
]

[[keyframes]]
frame = 267
strength = 0.7

[[keyframes]]
frame = 277

[[keyframes]]
frame = 287
strength = 0.0
masks = []


# ==================================================
# alice crawls into the rabbit hole (viewed from front)
[[keyframes]]
frame = 1128
prompt = "witch"
seed = 1640273403 # golden seed for frame 1187
strength = 0.0
masks = []

[[keyframes]]
frame = 1172
masks = [
    { center = [0.77, 0.566], radius = 0.2 }
]

[[keyframes]]
frame = 1177
masks = [
    { center = [0.77, 0.566], radius = 0.2 }
]
strength = "interpolate"

[[keyframes]]
frame = 1182
masks = [
    { center = [0.74, 0.666], radius = 0.2 }
]
strength = 0.65

[[keyframes]]
frame = 1197
masks = [
    { center = [0.75, 0.666], radius = 0.2 }
]
[[keyframes]]
frame = 1198
masks = [
    { center = [0.77, 0.6], radius = 0.2 }
]

[[keyframes]]
frame = 1200
masks = [
    { center = [0.79, 0.52], radius = 0.2 }
]

[[keyframes]]
frame = 1206
masks = [
    { center = [0.79, 0.5], radius = 0.2 }
]

[[keyframes]]
# she starts moving to the right here (eventually leaving the frame)
frame = 1220
masks = []
strength = 0.0


# ==================================================
# alice crawls deeper into the rabbit hole (side view)
# 1390: alice falls
# 1412: cat enters frame to look, slips down slope but catches herself
# 1500: peers after alice
[[keyframes]]
frame = 1264


# ==================================================
# cat peers down, as seen by alice (cat recedes into distance)
[[keyframes]]
frame = 1562
