in_dir = "n/a"
mask_dir = "n/a"
scratch_dir = "copy of 7 with motion - v1 - short"
out_dir = "outputs/e1_28"
width = 1024
height = 768
stride = 1
restart_from = 0


[[keyframes]]
frame = 0
seed = 2408416340
prompt = "abstract impossible chrome drippy sculpture fine art jewelry, concept art, 3D object, octane render, unreal engine, album art, by Alberto Seveso"
scale = 10
strength = 0.5
steps = 50
color_coherence = "LAB"

[[keyframes]]
duration = 1
seed = "random"
animation.zoom = 1.02             # multiplicative factor per frame
animation.translate = [0.0, 0.0]  # pixels per frame for X and Y
animation.rotate = -1.0           # degrees per frame (positive is CCW)

[[keyframes]]
duration = 300
animation.zoom = 0.98
animation.translate = [2.0, 0.0]
animation.rotate = 0.0
