in_dir = "/home/erik/Code/extern/InvokeAI/99f/mermaid_1/frames_1"
mask_dir = "/home/erik/Code/extern/InvokeAI/99f/mermaid_1/masks_1"
scratch_dir = "/home/erik/Code/extern/InvokeAI/99f/mermaid_1/scratch_1"
out_dir = "outputs/e1_18"
width = 1024
height = 768
stride = 1
restart_from = 728

[[keyframes]]
frame = 0
seed = 4035201747
prompt = "a colorful background with a lot of bubbles, concept art by rhads, behance contest winner, space art, outrun, psychedelic, retrowave"
scale = 7

[[keyframes]]
duration = 300
seed = 234590987

[[keyframes]]
duration = 300
seed = 564590987

[[keyframes]]
duration = 300
seed = 784590987
