in_dir = "/home/erik/Code/extern/InvokeAI/99f/mermaid_1/frames_1"
mask_dir = "/home/erik/Code/extern/InvokeAI/99f/mermaid_1/masks_1"
scratch_dir = "/home/erik/Code/extern/InvokeAI/99f/mermaid_1/scratch_1"
out_dir = "outputs/liquid_chrome_dreams"
width = 1024
height = 768
stride = 1

[[keyframes]]
frame = 0
seed = 8593426
prompt = "abstract impossible chrome drippy sculpture fine art jewelry with inlaid gold circuitry, concept art, infrared colors, 3D object, octane render, unreal engine, 8k, album art, by Alberto Seveso"
scale = 10.0

[[keyframes]]
duration = 250
seed = 9238456

[[keyframes]]
duration = 250
seed = 3547768

[[keyframes]]
duration = 250
seed = 4395603
