in_dir = "/home/erik/Code/extern/InvokeAI/99f/mermaid_1/frames_1"
mask_dir = "/home/erik/Code/extern/InvokeAI/99f/mermaid_1/masks_1"
scratch_dir = "/home/erik/Code/extern/InvokeAI/outputs/test/scratch_00"
out_dir = "outputs/test/clip_00"
width = 512
height = 512
stride = 1

[[keyframes]]
frame = 0
seed = 6890234
prompt = "a lush redwood forest with glowing orange mushrooms and verdant ferns, highly detailed digitial painting, cinematic lighting, fog and heavenly light rays, by artgerm, loish, greg rutkoski, and alphonse mucha"
scale = 7.5
strength = 0.5
masks = []

[[keyframes]]
duration = 1
animation.zoom = 1.02             # multiplicative factor per frame
animation.translate = [0.0, 0.0]  # pixels per frame for X and Y
animation.rotate = 0.0            # degrees per frame

[[keyframes]]
duration = 1
masks = []
seed = 9837623

[[keyframes]]
duration = 1
masks = []
seed = 8769

[[keyframes]]
duration = 1
masks = []
seed = 70678956

[[keyframes]]
duration = 1
masks = []
seed = 666424

[[keyframes]]
duration = 1
masks = []
seed = 290387

[[keyframes]]
duration = 1
masks = []
seed = 836520

[[keyframes]]
duration = 1
masks = []
seed = 309478

[[keyframes]]
duration = 1
masks = []
seed = 297853

[[keyframes]]
duration = 1
masks = []
seed = 1239487
