in_dir = "projects/davatar/not_used"
out_dir = "projects/davatar/outputs/life_with_ai/"
mask_in_dir = "projects/davatar/not_used"
width = 960
height = 576

[prompts]
life_with_ai = "a portrait of a beautiful cyborg woman, geometric surrealism, polygon tesselations, by james jean, by kim jung gi, symmetric, highly detailed, cinematic lighting"

[[keyframes]]
frame = 1
seed = 4099294540
prompt = "life_with_ai"
scale = 8.0
set_color_reference = true

[[keyframes]]
duration = 1
seed = "random"
input_image = "previous"
correct_colors = true
strength = 0.6
transform.zoom = 1.01
transform.translate = [0.0, 4.0]
transform.rotate = 0.0

[[keyframes]]
duration = 100
