in_dir = "projects/davatar/not_used"
out_dir = "projects/davatar/outputs/mind_and_body/"
mask_in_dir = "projects/davatar/not_used"
width = 960
height = 576

[prompts]
mind_and_body = "an earth goddess's face in profile made of colorful leaves, in the style of the dutch masters and gregory crewdson, by mark cooper, film grain texture, intricate detail, cinematic lighting, rim lighting"

[[keyframes]]
frame = 1
seed = 2107409691
prompt = "mind_and_body"
scale = 8.0
set_color_reference = true

[[keyframes]]
duration = 1
seed = "random"
input_image = "previous"
correct_colors = true
strength = 0.6
transform.zoom = 1.01
transform.translate = [4.0, 3.0]
transform.rotate = 0.0

[[keyframes]]
duration = 100
