in_dir = "/home/erik/Code/extern/InvokeAI/99f/mermaid_1/frames_1"
mask_dir = "/home/erik/Code/extern/InvokeAI/99f/mermaid_1/masks_1"
scratch_dir = "/home/erik/Code/extern/InvokeAI/99f/mermaid_1/scratch_1"
out_dir = "outputs/e1_10"
width = 1024
height = 768
stride = 1
restart_from = 0

[[keyframes]]
frame = 0
seed = 3285979822
prompt = "renaissance statue bright neon ring, digital art, 3 d render, ray tracing, hyper - realistic, hyper detailed, 8 k resolution, sharp focus"
scale = 7

[[keyframes]]
duration = 300
seed = 234590987

[[keyframes]]
duration = 300
seed = 564590987

[[keyframes]]
duration = 300
seed = 784590987
