in_dir = "projects/barbie/not_used"
out_dir = "projects/barbie/outputs/movie/"
mask_in_dir = "projects/barbie/not_used"
width = 640
height = 640

[prompts]
movie = "post-apocalyptic barbie with genetic mutations, hd screenshot inspired by H.R. Giger, octane render, ue5, raytracing, volumetric fog, detailed reflections, haze, unreal engine 5, IMAX quality, cinematic, epic lighting, dark, moody"

[[keyframes]]
frame = 0
seed = 3356715316
prompt = "movie"
scale = 8.0
set_color_reference = true

[[keyframes]]
duration = 1
seed = "random"
input_image = "previous"
correct_colors = true
strength = 0.6
transform.zoom = 1.0             # multiplicative factor per frame
transform.translate = [-3.0, 0.0]  # pixels per frame for X and Y
transform.rotate = 0.0            # revolutions per frame (positive is CCW)

[[keyframes]]
duration = 120
transform.zoom = 1.0
transform.translate = [1.0, -2.5]
transform.rotate = 0.000

[[keyframes]]
duration = 120
transform.zoom = 1.0
transform.translate = [1.0, -2.5]
transform.rotate = -0.005

[[keyframes]]
duration = 120
transform.zoom = 0.98
transform.translate = [3.0, 1.0]
transform.rotate = 0.005

[[keyframes]]
duration = 120
transform.zoom = 0.98
transform.translate = [-3.0, 2.0]
transform.rotate = 0.005

[[keyframes]]
duration = 120
transform.zoom = 1.02
transform.translate = [0.0, -3.0]
transform.rotate = 0.0

[[keyframes]]
duration = 120
transform.zoom = 1.02
transform.translate = [2.0, -3.0]
transform.rotate = 0.000

[[keyframes]]
duration = 120
transform.zoom = 1.0
transform.translate = [2.0, 0.0]
transform.rotate = -0.005

[[keyframes]]
duration = 120
transform.zoom = 0.98
transform.translate = [3.0, 1.0]
transform.rotate = 0.005

[[keyframes]]
duration = 120
transform.zoom = 0.98
transform.translate = [-3.0, 2.0]
transform.rotate = 0.005

[[keyframes]]
duration = 120
transform.zoom = 1.00
transform.translate = [0.0, -2.0]
transform.rotate = 0.0
