in_dir = "projects/barbie/not_used"
out_dir = "projects/barbie/outputs/nyc/"
mask_in_dir = "projects/barbie/not_used"
width = 640
height = 640

[prompts]
nyc = "post-apocalyptic barbie with genetic mutations, in new york city, new york city skyline, cinematic focus, polaroid photo, bleached vintage, very soft lights, vintage, pastel colors, high key lighting, soft lights, foggy, by steve hanks"

[[keyframes]]
frame = 0
seed = 911227346
prompt = "nyc"
scale = 8.0
set_color_reference = true

[[keyframes]]
duration = 1
seed = "random"
input_image = "previous"
correct_colors = true
strength = 0.6
transform.zoom = 1.02             # multiplicative factor per frame
transform.translate = [0.0, 0.0]  # pixels per frame for X and Y
transform.rotate = 0.0            # revolutions per frame (positive is CCW)

[[keyframes]]
duration = 120
transform.zoom = 1.02
transform.translate = [2.0, 0.0]
transform.rotate = 0.000

[[keyframes]]
duration = 120
transform.zoom = 1.02
transform.translate = [2.0, 0.0]
transform.rotate = -0.005

[[keyframes]]
duration = 120
transform.zoom = 0.98
transform.translate = [3.0, 1.0]
transform.rotate = 0.005

[[keyframes]]
duration = 120
transform.zoom = 0.98
transform.translate = [-3.0, 2.0]
transform.rotate = 0.005

[[keyframes]]
duration = 120
transform.zoom = 1.02
transform.translate = [0.0, -2.0]
transform.rotate = 0.0

[[keyframes]]
duration = 120
transform.zoom = 1.02
transform.translate = [2.0, 0.0]
transform.rotate = 0.000

[[keyframes]]
duration = 120
transform.zoom = 1.02
transform.translate = [2.0, 0.0]
transform.rotate = -0.005

[[keyframes]]
duration = 120
transform.zoom = 0.98
transform.translate = [3.0, 1.0]
transform.rotate = 0.005

[[keyframes]]
duration = 120
transform.zoom = 0.98
transform.translate = [-3.0, 2.0]
transform.rotate = 0.005

[[keyframes]]
duration = 120
transform.zoom = 1.02
transform.translate = [0.0, -2.0]
transform.rotate = 0.0
