in_dir = "/home/erik/Code/extern/InvokeAI/99f/mermaid_1/frames_1"
mask_dir = "/home/erik/Code/extern/InvokeAI/99f/mermaid_1/masks_1"
scratch_dir = "/home/erik/Code/extern/InvokeAI/99f/mermaid_1/scratch_1"
out_dir = "outputs/test5/clip_00"
width = 512
height = 512
stride = 1

[[keyframes]]
frame = 0
seed = 6890234
prompt = "something something greg rutkoski alphonse mucha"
scale = 7.5
strength = 0.0
masks = []

[[keyframes]]
frame = 100
masks = [
    { center = [0.25, 0.5], radius = 0.6 }
]

[[keyframes]]
duration = 20
strength = 0.3
masks = []

[[keyframes]]
duration = 50
strength = 0.8
animation.zoom = 1.1              # multiplicative factor per frame
animation.translate = [1.0, 0.0]  # pixels per frame for X and Y
animation.rotate = 1.0            # degrees per frame

[[keyframes]]
frame = 246
seed = "same"
seed_variations = [
    { seed = 472569, amount = 0.5 }
]

[[keyframes]]
frame = 260
seed = 1234
# Note that setting a seed implicitly resets the seed variations ("same" doesn't count).
# If you want to keep them, do this.
#seed_variations = "same"
strength = 0.1

[[keyframes]]
frame = 390
seed = 6890234
strength = 0.0
masks = []
