in_dir = "/home/erik/Code/extern/InvokeAI/99f/mermaid_1/frames_1"
mask_dir = "/home/erik/Code/extern/InvokeAI/99f/mermaid_1/masks_1"
scratch_dir = "/home/erik/Code/extern/InvokeAI/99f/mermaid_1/scratch_1"
out_dir = "outputs/e1_11"
width = 1024
height = 768
stride = 1
restart_from = 0

[[keyframes]]
frame = 0
seed = 1615971384
prompt = "3D abstract resin miniature sculpture by Salvador Dali, psychedelic, abstractionism, realistic, 8K, Hyperrealism, Subsurface scattering, raytracing, Octane Render, Zbrush, simple background"
scale = 7

[[keyframes]]
duration = 300
seed = 234590987

[[keyframes]]
duration = 300
seed = 564590987

[[keyframes]]
duration = 300
seed = 784590987
